---
title: My CV
---

<a href="kw_cv.pdf" download>Download</a>

# Education: #

**University of Pennsylvania, Philadelphia, PA (2019-Present)**  
Masters & Post-Baccalaureate Student  
Overall GPA: 4.00  

**The Ohio State University, Columbus, OH (2015-2018)**  
Bachelor of Arts, Spring 2018   
_summa cum laude_  
Major: Political Science  
Overall GPA: 4.00

***
# Awards & Honors #

* 2020: ABCT Dissemination and Implementation Science Special Interest Group  
Student Poster Award Finalist

* 2019: Dean’s List, University of Pennsylvania  

* 2018: Lawrence J. Herson Award, Ohio State University  
Funds ($500) awarded for academic excellence

* 2015-2018: Dean’s List, Ohio State University

***

# Publications #

1. Davis, M., Wolk, C. B., Jager-Hyman, S., Beidas, R. S., Young, J. F., Mautone, J. A., Buttenheim, A. M., Mandell, D. S., Volpp, K. G., **Wislocki, K.**, Futterer, A., Marx, D., Dieckmeyer, E. L., & Becker- Haimes, E. M. (2020). Implementing nudges for suicide prevention in real-world environments: project INSPIRE study protocol. Pilot and Feasibility Studies, 6, 143. https://doi.org/10.1186/s40814-020-00686-y.

2. Becker-Haimes, E. M., **Wislocki. K.**, DiDonato, S., Beidas, R.S., & Jensen-Doss, A. (revise & resubmit). Youth trauma histories are associated with under-diagnosis and under-treatment of co-occurring youth psychiatric symptoms. Journal of Clinical Child and Adolescent Psychology. 

3. Becker-Haimes, E. M., **Wislocki. K.**, DiDonato, S., & Jensen-Doss, A. (under review). Predictors of mental health clinicians’ self-efficacy in treating youth exposed to trauma. Journal of Traumatic Stress.

***

# Presentations #

1. Becker-Haimes, E. M., **Wislocki. K.**, DiDonato, S., Beidas, R.S., & Jensen-Doss, A. (2020, November). Clinician Diagnostic Bias: Obsessive-Compulsive Disorder is Misdiagnosed When There is a Co-occurring Trauma History.  In Buchholz, J. (Chair), Addressing Diagnostic Challenges in Obsessive-Compulsive Disorder, Psychosis, and Autism Spectrum Disorder. Symposium to be presented at the annual meeting of the Association for Behavioral and Cognitive Therapies, Philadelphia, PA.

2. Jager-Hyman, S., Becker-Haimes, E., Wolk, C. B., Davis, M., Beidas, R. S., **Wislocki, K.**, Futterer, A., Marx, D., Young, J. F., Mautone, K. A., & Buttenheim, A. M. (2020, November). Application of behavioral economics strategies to improve provider use of evidence-based suicide prevention strategies in primary care. In A. Dopp (Chair), Novel intervention and implementation approaches to improve behavioral health care access and outcomes in primary care settings. Symposium to be presented at the annual meeting of the Association for Behavioral and Cognitive Therapies, Philadelphia, PA. 

***

# Posters #

1. **Wislocki, K.**, Becker-Haimes, E. M., Wolk, C. B., Davis, M., Jager-Hyman, S., Futterer, A., Marx, D., Young, J. F., Mautone, J. A., Beidas, R. S. (2020). Variability in Attitudes towards Safety Planning Across Provider Type. Poster to be presented at the annual meeting of the Association for Behavioral and Cognitive Therapies Convention, Philadelphia, PA. 

2. **Wislocki, K.**, Jensen-Doss, A., DiDonato, S., Beidas, R. S., & Becker-Haimes, E. (2020). Youth Trauma Exposure and Under-Treatment of Co-Occurring Mental Health Concerns. Poster to be presented at the annual meeting of the Association for Behavioral and Cognitive Therapies Convention, Philadelphia, PA. 

3. Davis, M., Siegel, J., Becker-Haimes, E., Jager-Hyman, S., Beidas, R.S., **Wislocki, K.**, Futterer, A., Young, J.F., Mautone, J.A., Buttenheim, A.M., & Wolk, C.B. (2020). Barriers and facilitators to evidence-based suicide screening, assessment, and intervention in primary care and specialty mental health settings. Poster to be presented at the virtual Annual Conference on the Science of Dissemination and Implementation in Health. 

***

# Professional Experience #

**Clinical Research Coordinator, Center for Mental Health, Perelman School of Medicine at the University of Pennsylvania — Autumn 2019 – Present**

**PI: Dr. Emily Becker-Haimes**

- Serve as lead research coordinator for an NIMH-funded administrative supplement to the Penn ALACRITY Center aimed at improving implementation of evidence-based practices for suicide prevention  

- Oversee data collection, data analysis, and data management for multiple projects at the intersection of clinical psychology, implementation science, and behavioral economics  

- Lead design of a website to house materials to support suicide screening and assessment for use by community partners  

- Assist with grant-writing, research proposals, and manuscript submissions for current and future projects  

- Lead communication with community stakeholders for implementation projects  

- Provide support to other interdisciplinary projects at the Center for Mental Health  


**Academic Performance Analyst, Columbus City Schools — Autumn 2018 – Summer 2019**

- Conducted data collection, analysis, and reporting for 25+ urban public schools  

- Led instruction on data, programs, and professional development for educators and administrators in a public school district of 50,000+ students  

- Developed socio-emotional and academic data models for relevant stakeholders  

- Assisted with grant-writing, research proposals, program implementation, policy development, and school improvement efforts  

**Research Assistant, Ohio State University — Winter 2018 – Summer 2018**

**PI: Dr. Erin Lin**

- Lead research assistant on an interdisciplinary project analyzing the long-term impacts of conflict in Cambodia  

- Collaborated on-site in Cambodia with NGOs to perform data collection in areas contaminated with unexploded ordnance  

- Planned, conducted, and transcribed household interviews with community stakeholders  

- Contributed to research protocols, grant applications, and budget management   

**Marketing Intern, Virginia Arts Festival — Summer 2017**

- Performed social media management, copywriting, digital marketing, and data analytics for regional arts non-profit  

- Managed social media development, engagement, and reach/impact analysis; increased outreach and involvement across all platforms  

- Developed and launched new partnerships with community organizations  

**Office Assistant, Baker West Hall, Ohio State University — Autumn 2016 – Spring 2017**

- Served as an administrative liaison for 400+ person residence hall  

- Facilitated management of issues involving data, policy, security, and community development  

- Performed extensive duties relating to resident communication, university services, and initiative management  

**Intern, Office of the Fairfax County Chairman of the Board of Supervisors — Summer 2016**

- Managed administrative work for a government office serving a population of 1.13 million  

- Facilitated constituent communication, office data, political outreach, issues research, and media review

- Developed campaigns and presentations relating to legislative issues  

***

# Clinical Experience # 

**Resilience Coach, Coping First Aid Program, Perelman School of Medicine at the University of Pennsylvania —  Spring 2020 – Present**

- Provided brief psychosocial support via telehealth platform, grounded in principles of Psychological First Aid to individuals in and around Penn Medicine to support healthcare and other frontline workers experiencing distress as a result of the COVID-19 pandemic  

- Attended weekly supervision with a licensed psychologist  

 
**Resident Advisor, Baker West Hall, Ohio State University — Autumn 2017 – Spring 2018**

- Guided project/event planning, community engagement, and development for 400+ person residence hall  

- Led efforts related to administration, residence life, policy enforcement, and community involvement  

- Exercised crisis resolution and management functions  

***
# Professional Memberships #

- Association for Behavioral and Cognitive Therapies (ABCT)  

***
# Institutional Service & Other Experience #

**Coordinator, Workgroup to Improve Black Representation at the Penn Center for Mental Health — Summer 2020 – Present**

- Created, administered, and analyzed workplace survey data to inform workgroup agenda  

- Contributed to policy changes to increase Black representation within Penn’s Center for Mental Health  

- Assisted with creation and implementation of protocols to increase equity in hiring processes  

- Performed administrative tasks on behalf of the workgroup  

**Development Volunteer, Coping First Aid Program Perelman School of Medicine at University of Pennsylvania  — Spring 2020 – Present**

- Contributed to the development and expansion of the Coping First Aid program  

- Volunteered key administrative support to the Coping First Aid program under direct supervision of the Coping First Aid program directors to facilitate its rapid expansion   

**Advisor, Baker West Activities Council, Ohio State University — Summer 2018 – Spring 2019**

- Supervised community development and outreach for 400+ person residence hall  

- Executed project planning, marketing, oversight, and management of 50+ programs  

- Won various grants and awards for events (including Hall of the Year award — granted to one residence hall a year)  

- Acted as a mentor, leader, and advisor to executive board members  

**Teaching Assistant, Department of Philosophy, Ohio State University — Winter 2016 – Spring 2016**

- Directly assisted 50+ students who were struggling academically  

- Facilitated in-class support, strategic planning, and class attendance/ participation;
carried out data analysis and class-related administrative tasks  

- Contributed to lesson planning and curriculum development for multiple sections of ESEPHL 3410: Philosophy of Education  

***

# Skills #

- R (mastery) 

- SPSS (mastery) 

- Python (intermediate) 

- Excel (mastery) 

- REDCap (mastery) 

- Qualtrics (mastery) 


 



