---
title: Research
---

My research focuses on the intersection of mental health and advanced technologies. You can find past work of mine [here](https://scholar.google.com/citations?user=tV5UcbwAAAAJ&hl=en)

**Current Research Areas:**

**Enhancing dynamic prediction of mental health symptoms through individualized modeling strategies using technology**

Accurately predicting changes in mental health symptoms requires approaches that reflect each person's unique patterns. By using individualized modeling strategies powered by technology, we can monitor real-time data to anticipate symptom changes and intervene earlier—leading to more timely, personalized, and effective mental health care.

**Ensuring the safe and effective use of artificial intelligence with individuals experiencing mental health problems**

As AI continues to proliferate, ensuring their safety and effectiveness is critical, especially for vulnerable individuals. Robust design, clinical oversight, and ethical safeguards are essential to prevent harm, reduce bias, and support the use of this technology.

**Improving evidence-based mental health assessment and intervention for trauma-exposed populations**

Trauma exposure can negatively impact one's physical and mental health. Advancing evidence-based tools and interventions tailored to trauma-exposed populations helps ensure more accurate diagnosis, effective treatment, and better long-term outcomes for those who have experienced trauma.

**Increasing access to mental health care through technology**

Many people face barriers to accessing mental health care. Technology offers scalable, flexible solutions to help bridge these gaps, expanding access to support and resources for those who need care.




**You can find a copy of my CV below:**

<iframe src="CV_KW_091625.pdf" width="100%" height="600px">
  <a href="CV_KW_091625.pdf">Download PDF</a>.
</iframe>


 



